# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyStripToolAlt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pydm.widgets.byte import PyDMByteIndicator
from pydm.widgets.label import PyDMLabel
from pydm import Display
from scipy.ndimage import maximum_position


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1142, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signal_viewer_title = PyDMLabel(self.centralwidget)
        self.signal_viewer_title.setGeometry(QtCore.QRect(0, 10, 304, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signal_viewer_title.sizePolicy().hasHeightForWidth())
        self.signal_viewer_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.signal_viewer_title.setFont(font)
        self.signal_viewer_title.setToolTip("")
        self.signal_viewer_title.setObjectName("signal_viewer_title")
        self.current_time_date = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.current_time_date.setGeometry(QtCore.QRect(325, 24, 805, 23))
        self.current_time_date.setReadOnly(True)
        self.current_time_date.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.current_time_date.setCalendarPopup(True)
        self.current_time_date.setObjectName("current_time_date")
        self.time_plots_layout = QtWidgets.QGroupBox(self.centralwidget)
        self.time_plots_layout.setGeometry(QtCore.QRect(0, 71, 1130, 297))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_plots_layout.sizePolicy().hasHeightForWidth())
        self.time_plots_layout.setSizePolicy(sizePolicy)
        self.time_plots_layout.setObjectName("time_plots_layout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.time_plots_layout)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.signal_manipulation_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.signal_manipulation_group_box.setGeometry(QtCore.QRect(325, 377, 805, 263))
        self.signal_manipulation_group_box.setObjectName("signal_manipulation_group_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.signal_manipulation_group_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.signal_scroll_area_2 = QtWidgets.QScrollArea(self.signal_manipulation_group_box)
        self.signal_scroll_area_2.setWidgetResizable(True)
        self.signal_scroll_area_2.setObjectName("signal_scroll_area_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 775, 214))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SignalLayout_3 = QtWidgets.QVBoxLayout()
        self.SignalLayout_3.setObjectName("SignalLayout_3")
        self.verticalLayout_2.addLayout(self.SignalLayout_3)
        self.signal_scroll_area_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.signal_scroll_area_2, 0, 0, 2, 1)
        self.y_axis_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.y_axis_group_box.setGeometry(QtCore.QRect(0, 377, 316, 98))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_axis_group_box.sizePolicy().hasHeightForWidth())
        self.y_axis_group_box.setSizePolicy(sizePolicy)
        self.y_axis_group_box.setObjectName("y_axis_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.y_axis_group_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.y_axis_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.y_axis_group_box)
        self.spinBox_2.setMaximum(12)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_4.addWidget(self.spinBox_2)
        self.time_manipulation_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.time_manipulation_group_box.setGeometry(QtCore.QRect(0, 484, 316, 156))
        self.time_manipulation_group_box.setObjectName("time_manipulation_group_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.time_manipulation_group_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.start_time_select_2 = QtWidgets.QTimeEdit(self.time_manipulation_group_box)
        self.start_time_select_2.setObjectName("start_time_select_2")
        self.gridLayout_7.addWidget(self.start_time_select_2, 2, 2, 1, 3)
        self.minutes_label_2 = QtWidgets.QLabel(self.time_manipulation_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minutes_label_2.sizePolicy().hasHeightForWidth())
        self.minutes_label_2.setSizePolicy(sizePolicy)
        self.minutes_label_2.setObjectName("minutes_label_2")
        self.gridLayout_7.addWidget(self.minutes_label_2, 0, 9, 1, 1)
        self.days_label_2 = QtWidgets.QLabel(self.time_manipulation_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.days_label_2.sizePolicy().hasHeightForWidth())
        self.days_label_2.setSizePolicy(sizePolicy)
        self.days_label_2.setObjectName("days_label_2")
        self.gridLayout_7.addWidget(self.days_label_2, 0, 4, 1, 1)
        self.months_label_2 = QtWidgets.QLabel(self.time_manipulation_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.months_label_2.sizePolicy().hasHeightForWidth())
        self.months_label_2.setSizePolicy(sizePolicy)
        self.months_label_2.setObjectName("months_label_2")
        self.gridLayout_7.addWidget(self.months_label_2, 0, 2, 1, 1)
        self.months_selector_2 = QtWidgets.QSpinBox(self.time_manipulation_group_box)
        self.months_selector_2.setObjectName("months_selector_2")
        self.gridLayout_7.addWidget(self.months_selector_2, 1, 2, 1, 1)
        self.years_selector_2 = QtWidgets.QSpinBox(self.time_manipulation_group_box)
        self.years_selector_2.setObjectName("years_selector_2")
        self.gridLayout_7.addWidget(self.years_selector_2, 1, 0, 1, 1)
        self.pause_play_button_2 = QtWidgets.QPushButton(self.time_manipulation_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_play_button_2.sizePolicy().hasHeightForWidth())
        self.pause_play_button_2.setSizePolicy(sizePolicy)
        self.pause_play_button_2.setCheckable(True)
        self.pause_play_button_2.setObjectName("pause_play_button_2")
        self.gridLayout_7.addWidget(self.pause_play_button_2, 2, 5, 1, 2)
        self.days_selector_2 = QtWidgets.QSpinBox(self.time_manipulation_group_box)
        self.days_selector_2.setObjectName("days_selector_2")
        self.gridLayout_7.addWidget(self.days_selector_2, 1, 4, 1, 1)
        self.start_time_label_2 = QtWidgets.QLabel(self.time_manipulation_group_box)
        self.start_time_label_2.setObjectName("start_time_label_2")
        self.gridLayout_7.addWidget(self.start_time_label_2, 2, 0, 1, 1)
        self.pause_play_indicator_2 = PyDMByteIndicator(self.time_manipulation_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_play_indicator_2.sizePolicy().hasHeightForWidth())
        self.pause_play_indicator_2.setSizePolicy(sizePolicy)
        self.pause_play_indicator_2.setProperty("showLabels", False)
        self.pause_play_indicator_2.setObjectName("pause_play_indicator_2")
        self.gridLayout_7.addWidget(self.pause_play_indicator_2, 2, 9, 1, 1)
        self.minutes_selector_2 = QtWidgets.QSpinBox(self.time_manipulation_group_box)
        self.minutes_selector_2.setObjectName("minutes_selector_2")
        self.gridLayout_7.addWidget(self.minutes_selector_2, 1, 9, 1, 1)
        self.years_label_2 = QtWidgets.QLabel(self.time_manipulation_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.years_label_2.sizePolicy().hasHeightForWidth())
        self.years_label_2.setSizePolicy(sizePolicy)
        self.years_label_2.setObjectName("years_label_2")
        self.gridLayout_7.addWidget(self.years_label_2, 0, 0, 1, 1)
        self.hours_label_2 = QtWidgets.QLabel(self.time_manipulation_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hours_label_2.sizePolicy().hasHeightForWidth())
        self.hours_label_2.setSizePolicy(sizePolicy)
        self.hours_label_2.setObjectName("hours_label_2")
        self.gridLayout_7.addWidget(self.hours_label_2, 0, 5, 1, 1)
        self.hours_selector_2 = QtWidgets.QSpinBox(self.time_manipulation_group_box)
        self.hours_selector_2.setObjectName("hours_selector_2")
        self.gridLayout_7.addWidget(self.hours_selector_2, 1, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionDelete_2 = QtWidgets.QAction(MainWindow)
        self.actionDelete_2.setObjectName("actionDelete_2")
        self.menuFile.addAction(self.actionAdd)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionDelete)
        self.menuFile.addAction(self.actionDelete_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signal_viewer_title.setText(_translate("MainWindow", "Signal Viewer"))
        self.current_time_date.setToolTip(_translate("MainWindow", "Current time"))
        self.current_time_date.setDisplayFormat(_translate("MainWindow", "M/d/yyyy h:mm AP"))
        self.time_plots_layout.setTitle(_translate("MainWindow", "Time Plots"))
        self.signal_manipulation_group_box.setTitle(_translate("MainWindow", "Signal"))
        self.y_axis_group_box.setTitle(_translate("MainWindow", "Time Plot Management"))
        self.label_2.setText(_translate("MainWindow", "Number of time plots:"))
        self.time_manipulation_group_box.setTitle(_translate("MainWindow", "Time Manipulation"))
        self.minutes_label_2.setText(_translate("MainWindow", "Minutes"))
        self.days_label_2.setText(_translate("MainWindow", "Days"))
        self.months_label_2.setText(_translate("MainWindow", "Months"))
        self.months_selector_2.setToolTip(_translate("MainWindow", "Months"))
        self.years_selector_2.setToolTip(_translate("MainWindow", "Years"))
        self.pause_play_button_2.setToolTip(_translate("MainWindow", "Pause/Play Live View"))
        self.pause_play_button_2.setText(_translate("MainWindow", "Pause\n"
                                                    "Play"))
        self.pause_play_button_2.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.days_selector_2.setToolTip(_translate("MainWindow", "Days"))
        self.start_time_label_2.setText(_translate("MainWindow", "Start\n"
                                                   "Time"))
        self.pause_play_indicator_2.setToolTip(_translate("MainWindow", "Green is for Live View; gray is for static."))
        self.minutes_selector_2.setToolTip(_translate("MainWindow", "Minutes"))
        self.years_label_2.setText(_translate("MainWindow", "Years"))
        self.hours_label_2.setText(_translate("MainWindow", "Hours"))
        self.hours_selector_2.setToolTip(_translate("MainWindow", "Hours"))
        self.menuFile.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionDelete.setText(_translate("MainWindow", "Save"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionDelete_2.setText(_translate("MainWindow", "Delete"))
        self.actionDelete_2.setShortcut(_translate("MainWindow", "Ctrl+D"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
